kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-node-on-k3s
  namespace: hello-node-on-k3s
  labels:
    app: hello-node-on-k3s
    name: hello-node-on-k3s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-node-on-k3s
      task: hello-node-on-k3s
  template:
    metadata:
      labels:
        app: hello-node-on-k3s
        task: hello-node-on-k3s
    spec:
      containers:
        - name: hello-node-on-k3s
          image: 'docker.registry.private/test/hello-node-k3s:90e13e10'
          ports:
            - containerPort: 3000
