apiVersion: v1
kind: Service
metadata:
  name: hello-node-on-k3s
  namespace: hello-node-on-k3s

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: hello-node
    task: hello-node-on-k3s