apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-node-prod
  namespace: hello-node-on-k3s
spec:
  commonName: rpile3.bentell.se
  secretName: hello-node-prod
  dnsNames:
    - rpile3.bentell.se
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
