apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-node-on-k3s-cert
  namespace: hello-node-on-k3s
spec:
  commonName: rpile3.bentell.se
  secretName: hello-node-on-k3s-cert
  dnsNames:
    - rpile3.bentell.se
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
